version: "3"
services:
  api:
    image: node:12.18.4
    container_name: media_api
    working_dir: /home/node/media-api
    tty: true
    restart: "always"
    links:
    - redis:redis
    depends_on:
      - redis
    ports:
    - 4200:4200
    volumes:
    - ./server:/home/node/media-api
    entrypoint: /bin/bash
    command: -s

  redis:
    image: redis:5.0.3-alpine
    container_name: media_redis
    ports:
    - 6389:6379
    tty: true
    command: >
      --requirepass secret
    restart: "always"
